version: "2"
services:
  ci-api:
    build:
      context: ./srv/ci-api
    ports:
      - "80:80"
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./srv/ci-api:/var/www/html
      - ./srv/ci-api/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
    networks:
      - internal
    ports:
      - "3307:3306"

  go:
    build:
      context: ./srv/go
    ports:
      - "8080:8080"
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./srv/go:/go
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:
    driver: bridge
